#ifndef COUNTER_H
#define COUNTER_H

#define FIOSET_OFFSET 0x18
#define FIOPIN_OFFSET 0x14
#define FIOCLR_OFFSET 0x1C
#define FIO0SET_ADDRESS LPC_GPIO0_BASE + FIOSET_OFFSET // 0x2009C018 //C01A  // FIO0SET2
#define FIO0GET_ADDRESS LPC_GPIO0_BASE + FIOPIN_OFFSET
#define FIO0CLR_ADDRESS LPC_GPIO0_BASE + FIOCLR_OFFSET
#define LED_PIN 22 //6 //pin22

void setupCounter(void);

#endif
